### PR TITLE
Fix flake8 E231

### PR DESCRIPTION
**Pull request by MetRonnie**
For some reason, Flake8 was not detecting some problems on python 3.9.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] No dependency changes 
- [x] Tests are not needed
- [x] No changelog entry needed
- [x] No docs needed
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

File: .github/workflows/test_fast.yml [hunk 1]
```diff
@@ -130,7 +128,8 @@ jobs:
         run: etc/bin/shellchecker
 
       - name: MyPy
-        run: mypy
+        # specify --python-version to avoid errors regarding site-packages
+        run: mypy --python-version 3.8
```
Comment (oliver-sanders) [inline .github/workflows/test_fast.yml:132]: 3.7?

Comment (MetRonnie) [reply .github/workflows/test_fast.yml:132]:
```
$ mypy --python-version=3.7
[...]/python3.12/site-packages/matplotlib/pyplot.py:246: error: Assignment expressions are only supported in Python 3.8 and greater  [syntax]
Found 1 error in 1 file (errors prevented further checking)
```

I suppose to be safe we will have to split off mypy into its own job 😒

Comment (oliver-sanders) [reply .github/workflows/test_fast.yml:132]: > Assignment expressions are only supported in Python 3.8 and greater

I think mypy has reported a legit error here that the tests failed to spot! Thankfully this issue only applies to the developer main loop plugins so is of little consequence. Would introducing an upper pin on matplotlib clear the error?

Comment (MetRonnie) [reply .github/workflows/test_fast.yml:132]: This version of matplotlib would not install on Python 3.7 so there's no error here. It's just that Mypy can't work in Python 3.7 mode when it comes across 3.7-incompatible code in 3rd-party libraries: https://github.com/python/mypy/issues/9972

Comment (MetRonnie) [reply .github/workflows/test_fast.yml:132]: See also https://github.com/cylc/cylc-flow/issues/5736

Comment (MetRonnie) [reply .github/workflows/test_fast.yml]: Wait I just realised that since we moved to linting in its own job on GH Actions, we're not installing matplotlib during that job so this error is not raised anymore!

**Review by oliver-sanders — APPROVED** [review]

File: .github/workflows/test_fast.yml (hunk 1 above)
Comment (oliver-sanders) [reply .github/workflows/test_fast.yml]: Ach dammit, we should probably install the `all` group, one for another day...

**Comment by oliver-sanders** [comment]
(re-running the failed test)
